FROM python:3.12.1-slim

# Set the working directory to /code.
WORKDIR /code

# Copy the current directory to the /code directory.
COPY . /code

# Install gcc and other dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install --no-cache-dir poetry

# Use Poetry to install dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root

# Make port 8081 available to the world outside this container
EXPOSE 8081

# Healthcheck
HEALTHCHECK --interval=5s --timeout=5s --retries=3 \
    CMD curl -f http://localhost:8081/health || exit 1

# Run the uvicorn command, telling it to use the app object imported from app.main.
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081", "--reload", "--reload-exclude", "app/test_main.py"]

# CMD ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8081" "--reload", "--reload-exclude", "app/test_main.py"]
